"""
Snakemake script to automate resfinder runs for multiple samples
"""

# Get configuration file

# config exported from conda
# configfile: "config/juno_amr_master.yml"

#current testing config
configfile: "config/config.yml"

# config created with python wrapper based on user input
# configfile: "config/user_parameters"

# Get includes
include: "bin/rules/runResfinderFastq.smk"
include: "bin/rules/runResfinderFasta.smk"

rule all:
    """ Main rule that starts the complete workflow """
    input: 
        #These filenames are generated by resfinder, these are the most important files i think, but we could add all output files
        # expand("output/{sample}/PointFinder_results.txt", sample=config["samples_fasta"]),
        expand("output/{sample}/PointFinder_results.txt", sample=config["samples_fastq_r1"])
