"""
Juno-amr
Authors: Roxanne Wolthuis ....
Organization: Rijksinstituut voor Volksgezondheid en Milieu (RIVM)
Department: Infektieziekteonderzoek, Diagnostiek en Laboratorium Surveillance (IDS), Bacteriologie (BPD)
Date: 30 - 03 - 2021
"""

#################################################################################
#####   Import config file                                                  #####
#################################################################################
configfile: "config/user_parameters.yml"

#################################################################################
#####   Load processes                                                      #####
#################################################################################
include: "bin/rules/runResfinderFastq.smk"
#include: "bin/rules/runResfinderFasta.smk"

#################################################################################
#####   Specify final output                                                #####
#################################################################################
rule all:
    """ Main rule that starts the complete workflow """
    input: 
        #These filenames are generated by resfinder, these are the most important files i think, but we could add all output files
        # expand("output/{sample}/ResFinder_results.txt", sample=config["samples_fasta"]),
        expand("output/{sample}/ResFinder_results.txt", sample=config["samples_fastq_r1"])
