__package_name__ = "juno_amr"
__authors__ = "Roxanne Wolthuis & Alejandra Hernández Segura "
__email__ = "roxanne.wolthuis@rivm.nl"
__license__ = "AGPLv3"
__version__ = "1.0"
__description__ = "Juno-amr pipeline. Automated pipeline for bacterial AMR analysis."