#fastqr1
samples_fastq_r1:
  '1091901608': /mnt/scratch_dir/wolthuir/amr_testdata_irods/input/1091901608_pR1.fastq.gz
  '1091901865': /mnt/scratch_dir/wolthuir/amr_testdata_irods/input/1091901865_pR1.fastq.gz
  1091901335_Sen_BSR_EPI_48477-H04_ACAGTGTATGGAACATACGG_L001: /mnt/scratch_dir/wolthuir/amr_testdata_irods/input/1091901335_Sen_BSR_EPI_48477-H04_ACAGTGTATGGAACATACGG_L001_pR1.fastq.gz
  1091900558_S4_L001: /mnt/scratch_dir/wolthuir/amr_testdata_irods/input/1091900558_S4_L001_pR1.fastq.gz


#fastqr2
samples_fastq_r2:
  '1091901865': /mnt/scratch_dir/wolthuir/amr_testdata_irods/input/1091901865_pR2.fastq.gz
  1091901335_Sen_BSR_EPI_48477-H04_ACAGTGTATGGAACATACGG_L001: /mnt/scratch_dir/wolthuir/amr_testdata_irods/input/1091901335_Sen_BSR_EPI_48477-H04_ACAGTGTATGGAACATACGG_L001_pR2.fastq.gz
  '1091901608': /mnt/scratch_dir/wolthuir/amr_testdata_irods/input/1091901608_pR2.fastq.gz
  1091900558_S4_L001: /mnt/scratch_dir/wolthuir/amr_testdata_irods/input/1091900558_S4_L001_pR2.fastq.gz

# parameters for pipeline given by user
Parameters:
  output_dir: /mnt/scratch_dir/wolthuir/amr_testdata_irods/outt
  input_dir: /mnt/scratch_dir/wolthuir/amr_testdata_irods/input
  species: salmonella
  coverage: 0.6
  threshold: 0.8
  pointfinder_db: /mnt/db/juno-amr/pointfinderdb
  resfinder_db: /mnt/db/juno-amr/resfinderdb
  db_update: false
  run_pointfinder: '1'
  dryrun: false
  queue: bio
  input_isfastq_boolean: true
