#fastqr1
samples_fastq_r1:
  '1071900063': testdata/fastq_zipped/1071900063_pR1.fastq.gz


#fastqr2
samples_fastq_r2:
  '1071900063': testdata/fastq_zipped/1071900063_pR2.fastq.gz

# parameters for pipeline given by user
Parameters:
  output_dir: output
  input_dir: testdata/fastq_zipped
  species: salmonella
  coverage: 0.6
  threshold: 0.8
  pointfinder_db: /mnt/db/juno-amr/pointfinderdb
  resfinder_db: /mnt/db/juno-amr/resfinderdb
  db_update: false
  run_pointfinder: '1'
  dryrun: false
  input_isfastq_boolean: true
