#fastqr1
samples_fastq_r1:
  '1071900063': testdata/fastq_zipped/1071900063_pR1.fastq.gz
  '1171900012': testdata/fastq_zipped/1171900012_pR1.fastq.gz


#fastqr2
samples_fastq_r2:
  '1171900012': testdata/fastq_zipped/1171900012_pR2.fastq.gz
  '1071900063': testdata/fastq_zipped/1071900063_pR2.fastq.gz

# parameters for pipeline given by user
Parameters:
  output_dir: testing_with_shell_final
  input_dir: testdata/fastq_zipped
  species: escherichia coli
  coverage: 0.6
  threshold: 0.8
  pointfinder_db: ../../../db/resfinder/db_pointfinder
  resfinder_db: ../../../db/resfinder/db_resfinder
  run_pointfinder: '1'

