#fastqr1
samples_fastq_r1:
  '1071900063': testdata/fastq_zipped/1071900063_pR1.fastq.gz
  '1171900012': testdata/fastq_zipped/1171900012_pR1.fastq.gz
  1401R17682_S61_L555: testdata/fastq_zipped/1401R17682_S61_L555_R1_001.fastq.gz


#fastqr2
samples_fastq_r2:
  '1171900012': testdata/fastq_zipped/1171900012_pR2.fastq.gz
  1401R17682_S61_L555: testdata/fastq_zipped/1401R17682_S61_L555_R2_001.fastq.gz
  '1071900063': testdata/fastq_zipped/1071900063_pR2.fastq.gz

# parameters for pipeline given by user
Parameters:
  output_dir: output
  input_dir: testdata/fastq_zipped
  species: salmonella
  coverage: 0.6
  threshold: 0.8
  pointfinder_db: /mnt/db/resfinder/db_pointfinder
  resfinder_db: /mnt/db/resfinder/db_resfinder
  run_pointfinder: '1'
  dryrun: false
  input_isfastq_boolean: true
