#fasta
samples_fasta:
  '1122000006': /mnt/scratch_dir/wolthuir/amr_testdata_irods/input/fasta/1122000009.fasta
  '1122000001': /mnt/scratch_dir/wolthuir/amr_testdata_irods/input/fasta/1122000009.fasta
  '1122000009': /mnt/scratch_dir/wolthuir/amr_testdata_irods/input/fasta/1122000009.fasta

# parameters for pipeline given by user
Parameters:
  output_dir: /mnt/scratch_dir/wolthuir/amr_testdata_irods/outt
  input_dir: /mnt/scratch_dir/wolthuir/amr_testdata_irods/input/fasta
  species: salmonella
  coverage: 0.6
  threshold: 0.8
  pointfinder_db: /mnt/db/juno-amr/pointfinderdb
  resfinder_db: /mnt/db/juno-amr/resfinderdb
  db_update: false
  run_pointfinder: '1'
  dryrun: false
  queue: bio
  input_isfastq_boolean: false
