#fastqr1
samples_fastq_r1:
  '1171900012': testdata/fastq_zipped/1171900012_R1.fastq.gz
  '1071900063': testdata/fastq_zipped/1071900063_R1.fastq.gz


#fastqr2
samples_fastq_r2:
  '1071900063': testdata/fastq_zipped/1071900063_R2.fastq.gz
  '1171900012': testdata/fastq_zipped/1171900012_R2.fastq.gz

# parameters for pipeline given by user
Parameters:
  input_dir: testdata/fastq_zipped
  species: Escherichia coli
  coverage: 0.6
  threshold: 0.8

